### ISSUE TITLE
 Data  Explorer Page - Selecting different study filters results in files with inconsistent columns in the TSV. 

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/portal#304] opened 2022-07-29 15:34 UTC
Steps to reproduce: 

1. Go to the https://virusseq-dataportal.ca/explorer and Select Study Id = `KHSC-ON ` 
2. Select download Metadata & fasta 
3. Select Study Id = `ABPL-AB` and some other filter to reduce the number of results. 
4. . Select download Metadata & fasta 
5. The TSV for Study ID = `KHSC-ON` doesnt have the Column `Submission Date`, while the TSV for Study ID= `ABPL-AB` has the `Submission Date' Column  

Expected Behavior: 
All/Any filters should produce the TSV with the same number of columns.

**Comment by leoraba** [comment] 2023-01-30 22:42
Not able to reproduce this issue. Closing this issue.

**Closed by leoraba** 2023-01-30 22:42 UTC
Labels: bug, prod, needs-investigation
